#!/bin/bash
# lib/common.sh — engine detection, the compose() wrapper, ramalama
# resolution, port allocation, and shadow models.json generation.
#
# Picks Podman by default, falls back to Docker if podman isn't found,
# and layers compose.mounts.override.yaml and compose.session.override.yaml
# on top (if present) so extra/session mounts never override the base ones
# defined in compose.yaml.

ENGINE="podman"
COMPOSE_CMD="podman-compose"

command -v podman &> /dev/null || { ENGINE="docker"; COMPOSE_CMD="docker compose"; }

compose() {
    local files=(-f "$DIR/compose.yaml")
    [ -f "$DIR/compose.mounts.override.yaml" ]  && files+=(-f "$DIR/compose.mounts.override.yaml")
    [ -f "$DIR/compose.session.override.yaml" ] && files+=(-f "$DIR/compose.session.override.yaml")
    $COMPOSE_CMD "${files[@]}" "$@"
}

# Makes sure 'ramalama' is resolvable even when the calling process (e.g.
# VSCode spawning the pi wrapper) doesn't inherit the interactive shell's
# PATH: checks PATH, then RAMALAMA_BIN_DIR, then common install locations.
resolve_ramalama() {
    command -v ramalama >/dev/null 2>&1 && return 0

    local CANDIDATES=(
        "${RAMALAMA_BIN_DIR:-}"
        "$HOME/.local/bin"
        "$HOME/.local/pipx/venvs/ramalama/bin"
        "/usr/local/bin"
        "/usr/bin"
    )
    for dir in "${CANDIDATES[@]}"; do
        if [ -n "$dir" ] && [ -x "$dir/ramalama" ]; then
            export PATH="$dir:$PATH"
            return 0
        fi
    done

    echo "[Error] 'ramalama' not found in PATH or common install locations." >&2
    echo "        Set RAMALAMA_BIN_DIR in env.conf to its install directory." >&2
    return 1
}

bootstrap_config() {
    resolve_ramalama || exit 1
    [ "${SKIP_ENSURE_ENV:-0}" = "1" ] || ensure_environment
    MODEL_PORT="${MODEL_PORT:-8080}"
    export MODEL_PORT
}

# Renders conf/pi-mounts.conf into a compose override that appends those
# volumes to pi-agent. ensure_environment() calls this automatically on
# every --setup/--start, so it stays current without a manual step.
render_mounts() {
    local SRC="$DIR/conf/pi-mounts.conf"
    local OUT="$DIR/compose.mounts.override.yaml"
    [ -f "$SRC" ] || { echo "[Mounts] No pi-mounts.conf found, skipping."; return 0; }

    {
        echo "# Auto-generated by pi-ramalama --render-mounts from pi-mounts.conf. Do not edit."
        echo "services:"
        echo "  pi-agent:"
        echo "    volumes:"
        local n=0
        while IFS= read -r line; do
            line="${line%%#*}"
            line="$(echo "$line" | xargs)"
            [ -z "$line" ] && continue
            line="${line/#\~/$HOME}"
            echo "      - ${line}"
            n=$((n+1))
        done < "$SRC"
        [ "$n" -eq 0 ] && echo "      []"
    } > "$OUT"
    echo "[Mounts] Rendered $n extra mount(s) from pi-mounts.conf -> $OUT"
}

# Signals (does not install) missing host dependencies.
# Runs on every pi-ramalama invocation.
check_dependencies() {
    local MISSING=0

    if ! command -v podman &>/dev/null && ! command -v docker &>/dev/null; then
        echo "[Missing] No OCI engine found (podman or docker)." >&2
        echo "           Install one, e.g.: sudo apt install podman" >&2
        MISSING=1
    fi

    if ! resolve_ramalama 2>/dev/null; then
        echo "[Missing] 'ramalama' CLI not found." >&2
        echo "           Install it: pipx install ramalama  (or: pip3 install --user ramalama)" >&2
        echo "           Or run: $DIR/requirements.sh" >&2
        MISSING=1
    fi

    if ! command -v curl &>/dev/null; then
        echo "[Missing] 'curl' not found (required by pi-ramalama's healthchecks)." >&2
        MISSING=1
    fi

    [ "$MISSING" -eq 0 ]
}

# Drops a stale pi-agent container (exists but not running) before a fresh
# 'compose up', so a leftover from a previous crash doesn't block the start.
ensure_pi_agent_removed() {
    if $ENGINE ps -a --format '{{.Names}}' 2>/dev/null | grep -qx pi-agent \
       && ! $ENGINE ps --format '{{.Names}}' 2>/dev/null | grep -qx pi-agent; then
        $ENGINE rm -f pi-agent >/dev/null 2>&1 || true
    fi
}

# ---------------------------------------------------------------------------
# Port allocation for concurrent 'ramalama serve' instances
# ---------------------------------------------------------------------------

# Tests whether TCP port $1 on localhost is currently free.
port_is_free() {
    local port="$1"
    if (exec 3<>"/dev/tcp/127.0.0.1/${port}") 2>/dev/null; then
        exec 3>&- 2>/dev/null
        return 1
    fi
    return 0
}

# Picks a free TCP port
find_free_port() {
    local base="$1"
    local range="${2:-2000}"
    local attempts="${3:-30}"
    local port
    for ((i = 0; i < attempts; i++)); do
        port=$((base + (RANDOM % range)))
        [ "$port" -lt 1024 ] && continue
        if port_is_free "$port"; then
            echo "$port"
            return 0
        fi
    done
    echo "[Error] Could not find a free port within ${range} of ${base} after ${attempts} attempts." >&2
    return 1
}

REAL_MODELS_JSON="$HOME/.pi/agent/models.json"

# CONFIRMED empirically (live 'ramalama serve' with no positional MODEL,
# no --models-preset, no --models-dir): the router auto-discovers every
# locally pulled model from its own store and registers each under a
# deterministic name — "<scheme>-<org>-<repo>-<quant>", built by replacing
# '/' and ':' in the bare model identifier with '-' and prefixing the
# registry scheme. Confirmed as "huggingface-" for models pulled with no
# explicit scheme prefix (this project's actual usage — every entry in
# models.conf is bare). ollama:// / oci:// prefixes are UNCONFIRMED and
# would need their own live test; ROUTER_MODELS as built by session.sh is
# always scheme-stripped already, so this only ever produces the
# confirmed "huggingface-" form in practice today regardless.
#
# Because a hand-authored preset section whose header matches that
# derived name overrides ramalama's own auto-discovered entry (per
# tools/server/README.md: "If the key corresponds to an existing model on
# the server, this will be used as the default config for that model"),
# NO 'model =' / container-path key is needed at all for any model this
# project pulls via 'ramalama pull'. This replaces the earlier
# unverified container-path placeholder entirely.
router_preset_section_name() {
    local raw="$1"
    local scheme="huggingface"
    if [[ "$raw" =~ ^([a-z]+)://(.*)$ ]]; then
        # Unreached in current usage (ROUTER_MODELS is always
        # scheme-stripped before this is called) — kept for
        # forward-compatibility, but this branch is UNVERIFIED.
        scheme="${BASH_REMATCH[1]}"
        raw="${BASH_REMATCH[2]}"
    fi
    raw="${raw//\//-}"
    raw="${raw//:/-}"
    echo "${scheme}-${raw}"
}

# Renders conf/models-preset.ini: one [section] per entry in ROUTER_MODELS,
# header matching ramalama's own auto-discovery naming (see
# router_preset_section_name() above), body filled from
# MODEL_PARAMS[<model>] (or DEFAULT_MODEL_PARAMS as fallback).
# LLAMA_ARG_* keys need no translation: llama.cpp's own --models-preset
# format accepts environment-variable-style keys verbatim (confirmed:
# tools/server/README.md's worked example uses 'LLAMA_ARG_CACHE_RAM = 0'
# as a section key), and MODEL_PARAMS already stores exactly that format
# — this only reformats KEY=VALUE to KEY = VALUE, one pair per line,
# skipping empty fields from any doubled-comma entries.
#
# DEFAULT_RAMALAMA_ENV is deliberately NOT included here: it mixes real
# llama.cpp LLAMA_ARG_* options with raw backend env vars (e.g.
# GGML_KLEIDIAI_SME) that the preset's option table has no guaranteed
# mapping for and could silently drop. It stays on --env at the router
# process level in _serve_router(), same as the old single-instance code.
render_models_preset() {
    local preset_path="$DIR/conf/models-preset.ini"
    {
        echo "version = 1"

        local model section params pair
        for model in "${ROUTER_MODELS[@]}"; do
            section="$(router_preset_section_name "$model")"
            echo
            echo "[$section]"
            params="${MODEL_PARAMS[$model]:-$DEFAULT_MODEL_PARAMS}"
            local IFS=','
            for pair in $params; do
                [ -n "$pair" ] && echo "${pair/=/ = }"
            done
            unset IFS
        done
    } > "$preset_path"
    echo "[Router] Preset written -> $preset_path (${#ROUTER_MODELS[@]} model section(s))"
}

# Builds a temporary models.json: the real one (if present) plus a single
# router provider entry exposing every model in ROUTER_MODELS as
# 'models: [{id,name},...]' under one baseUrl, added only if that baseUrl
# isn't already registered under an existing provider. Router mode means
# one endpoint for however many models are configured, unlike the old
# one-provider-per-instance scheme. The merge runs inside pi-sandbox-image
# (already built, already has python3 per pi-dev/Dockerfile) — no host
# jq/python3 dependency. Sets SESSION_MODELS_JSON on success; caller must
# check the return code.
render_shadow_models_json() {
    local MERGE_DIR
    MERGE_DIR="$(mktemp -d -t pi-ramalama-models-XXXXXX)" || return 1
    SESSION_MODELS_JSON="$MERGE_DIR/models.json"

    local MODELS_ARRAY_JSON="[" sep="" m id
    for m in "${ROUTER_MODELS[@]}"; do
        id="$(router_preset_section_name "$m")"
        MODELS_ARRAY_JSON+="${sep}{\"id\":\"${id}\",\"name\":\"${m}\"}"
        sep=","
    done
    MODELS_ARRAY_JSON+="]"

    cat > "$MERGE_DIR/new_provider.json" <<EOF
{"key":"session-${ROUTER_NAME}","baseUrl":"http://${ROUTER_NAME}:${ROUTER_PORT}/v1","models":${MODELS_ARRAY_JSON}}
EOF

    cat > "$MERGE_DIR/merge.py" << 'PYEOF'
import json, pathlib, sys

base_path = pathlib.Path("/base/models.json")
new_path = pathlib.Path("/work/new_provider.json")
out_path = pathlib.Path("/work/models.json")

data = {"providers": {}}
if base_path.exists():
    try:
        data = json.loads(base_path.read_text())
    except json.JSONDecodeError as exc:
        print(f"[Warning] Real models.json is not valid JSON, starting from empty: {exc}", file=sys.stderr)
        data = {"providers": {}}
data.setdefault("providers", {})

entry = json.loads(new_path.read_text())
existing_base_urls = {
    p.get("baseUrl") for p in data["providers"].values() if isinstance(p, dict)
}

if entry["baseUrl"] not in existing_base_urls:
    data["providers"][entry["key"]] = {
        "baseUrl": entry["baseUrl"],
        "api": "openai-completions",
        "apiKey": "not-needed",
        "models": entry["models"],
    }
    print(f"[Merge] Router provider added with {len(entry['models'])} model(s).", file=sys.stderr)
else:
    print("[Merge] Router baseUrl already present, skipped.", file=sys.stderr)

out_path.write_text(json.dumps(data, indent=2))
PYEOF

    local -a MOUNTS=(-v "$MERGE_DIR:/work:Z")
    [ -f "$REAL_MODELS_JSON" ] && MOUNTS+=(-v "$REAL_MODELS_JSON:/base/models.json:ro,Z")

    if ! $ENGINE run --rm "${MOUNTS[@]}" --entrypoint python3 pi-sandbox-image /work/merge.py; then
        echo "[Error] Failed to build shadow models.json." >&2
        rm -rf "$MERGE_DIR"
        SESSION_MODELS_JSON=""
        return 1
    fi
    echo "[Session] Shadow models.json ready (router, ${#ROUTER_MODELS[@]} model(s)) -> $SESSION_MODELS_JSON"
}

# Renders an ephemeral compose override that shadows
# /root/.pi/agent/models.json with the merged file above, read-only, for
# this session's pi-agent container only — same layering mechanism
# conf/pi-mounts.conf already uses (target is a file inside a mounted
# directory, more specific than the directory mount, so it takes
# precedence). Never edits conf/pi-mounts.conf or the real models.json.
render_session_override() {
    local OUT="$DIR/compose.session.override.yaml"
    {
        echo "# Auto-generated per-session by pi-ramalama. Ephemeral — torn"
        echo "# down with the session. Do not edit or commit."
        echo "services:"
        echo "  pi-agent:"
        echo "    volumes:"
        echo "      - ${SESSION_MODELS_JSON}:/root/.pi/agent/models.json:ro,Z"
        [ -n "${SESSION_SETTINGS_JSON:-}" ] && \
            echo "      - ${SESSION_SETTINGS_JSON}:/workspace/.pi/settings.json:ro,Z"
    } > "$OUT"
    echo "[Session] Mounted shadow models.json${SESSION_SETTINGS_JSON:+ and project settings.json} for this session."
}


# Removes the ephemeral compose override and the temp dir holding the
# merged models.json. Safe to call even if neither was ever created.
remove_session_artifacts() {
    rm -f "$DIR/compose.session.override.yaml"
    if [ -n "${SESSION_MODELS_JSON:-}" ]; then
        rm -rf "$(dirname "$SESSION_MODELS_JSON")" 2>/dev/null || true
        SESSION_MODELS_JSON=""
    fi
    if [ -n "${SESSION_SETTINGS_JSON:-}" ]; then
        rm -rf "$(dirname "$SESSION_SETTINGS_JSON")" 2>/dev/null || true
        SESSION_SETTINGS_JSON=""
    fi
}



REAL_PROJECT_SETTINGS_JSON="$PI_RAMALAMA_WD/.pi/settings.json"

# Generates an ephemeral project-level settings.json: the real project
# settings.json (if present) with defaultModel pinned to the first model
# selected this session. Relies on the same containerized-merge pattern as
# render_shadow_models_json so a user-authored
# .pi/settings.json is preserved verbatim except for that
# one key. Sets SESSION_SETTINGS_JSON on success.
render_session_settings() {
    if [ "${#ROUTER_MODELS[@]}" -eq 0 ]; then
        echo "[Session] No specific model selected (router will auto-serve everything local); leaving defaultModel untouched."
        SESSION_SETTINGS_JSON=""
        return 0
    fi

    local MERGE_DIR
    MERGE_DIR="$(mktemp -d -t pi-ramalama-settings-XXXXXX)" || return 1
    SESSION_SETTINGS_JSON="$MERGE_DIR/settings.json"

    cat > "$MERGE_DIR/merge.py" << 'PYEOF'
import json, pathlib, sys

base_path = pathlib.Path("/base/settings.json")
out_path = pathlib.Path("/work/settings.json")
default_model = sys.argv[1]

data = {}
if base_path.exists():
    try:
        data = json.loads(base_path.read_text())
    except json.JSONDecodeError as exc:
        print(f"[Warning] Real project settings.json is not valid JSON, starting from empty: {exc}", file=sys.stderr)
        data = {}

data["defaultModel"] = default_model
out_path.write_text(json.dumps(data, indent=2))
print(f"[Merge] Project settings.json defaultModel -> {default_model}", file=sys.stderr)
PYEOF

    local -a MOUNTS=(-v "$MERGE_DIR:/work:Z")
    [ -f "$REAL_PROJECT_SETTINGS_JSON" ] && MOUNTS+=(-v "$REAL_PROJECT_SETTINGS_JSON:/base/settings.json:ro,Z")

    if ! $ENGINE run --rm "${MOUNTS[@]}" --entrypoint python3 pi-sandbox-image \
        /work/merge.py "$(router_preset_section_name "${ROUTER_MODELS[0]}")"; then
        echo "[Error] Failed to build shadow project settings.json." >&2
        rm -rf "$MERGE_DIR"
        SESSION_SETTINGS_JSON=""
        return 1
    fi
    echo "[Session] Shadow project settings.json ready -> $SESSION_SETTINGS_JSON"
}
