#!/bin/bash
# lib/env.sh: host bootstrap (idempotent), extensions, destructive teardown.

# Renders conf/pi-mounts.conf into compose.mounts.override.yaml.
render_mounts() {
    local src="$DIR/conf/pi-mounts.conf" out="$DIR/compose.mounts.override.yaml" line n=0
    [ -f "$src" ] || { echo "[Mounts] No pi-mounts.conf found, skipping."; return 0; }
    {
        echo "# Auto-generated by pi-ramalama --render-mounts from pi-mounts.conf. Do not edit."
        printf 'services:\n  pi-agent:\n    volumes:\n'
        while IFS= read -r line || [ -n "$line" ]; do
            line="$(trim "$line")"
            [ -z "$line" ] && continue
            echo "      - ${line/#\~/$HOME}"
            n=$((n+1))
        done < "$src"
        [ "$n" -eq 0 ] && echo "      []"
    } > "$out"
    echo "[Mounts] Rendered $n extra mount(s) from pi-mounts.conf -> $out"
}

# Safe on every run: creates only what's missing, links the host
# wrappers, builds pi-sandbox-image only if absent.
ensure_environment() {
    render_mounts
    mkdir -p "$HOME/.pi/agent/skills" "$HOME/.pi/agent/extensions" \
             "$HOME/.config/cortexkit" "$HOME/.local/share/cortexkit/magic-context" \
             "$HOME/.local/bin" "$PI_RAMALAMA_WD/.pi"
    [ -f "$HOME/.pi/settings.json" ] || echo "{}" > "$HOME/.pi/settings.json"

    # Symlinks, not generated copies: both scripts resolve the repo via
    # readlink -f, so there is nothing to regenerate when the repo changes.
    local src dst
    for src in lib/pi-wrapper.sh:pi pi-ramalama:pi-ramalama; do
        dst="$HOME/.local/bin/${src#*:}"; src="$DIR/${src%%:*}"
        if [ "$(readlink -f "$dst")" != "$src" ]; then
            echo "[Auto-Setup] Linking $dst -> $src"
            ln -sfn "$src" "$dst"
        fi
    done

    if ! $ENGINE image inspect pi-sandbox-image >/dev/null 2>&1; then
        echo "[Auto-Setup] Image 'pi-sandbox-image' not found. Building..."
        compose build pi-agent
    fi
}

# Runs each line of pi-extensions.conf inside pi-agent with a TTY, so
# interactive prompts work. Failures are collected, not fatal.
install_extensions() {
    local src="$DIR/conf/pi-extensions.conf" cmd n=0 failed=()
    [ -f "$src" ] || { echo "[Error] pi-extensions.conf not found." >&2; exit 1; }
    bootstrap_config
    is_running pi-agent || { echo "[Extensions] pi-agent not running, starting it (no model needed)..."; start_pi_agent; }

    while IFS= read -r cmd <&3 || [ -n "$cmd" ]; do
        cmd="$(trim "$cmd")"
        [ -z "$cmd" ] && continue
        n=$((n+1))
        echo "[Extensions] ($n) $cmd"
        $ENGINE exec -it pi-agent bash -c "$cmd" || { echo "[Extensions] Command failed: $cmd" >&2; failed+=("$cmd"); }
    done 3< "$src"

    echo "[Extensions] Done: $n command(s) run, ${#failed[@]} failed."
    [ "${#failed[@]}" -eq 0 ] || { printf '  - %s\n' "${failed[@]}"; return 1; }
}

# Destroys containers, volumes (including extension volumes) and images.
remove_env() {
    echo "[Remove] Destroying containers and volumes..."
    compose down -v
    echo "[Remove] Cleaning up images..."
    $ENGINE rmi pi-sandbox-image || true
    $ENGINE rmi llama-optimus-sandbox || true
}
